### ISSUE TITLE
test262 harness tests failing

### ISSUE THREAD

**Issue by avdg** [bterlson/eshost#10]
Running test262\test\harness\**\*.js on node using test262-harness currently results in this result on my machine

```js
Ran 120 tests
53 passed
67 failed
```

Using the python runner I get 0.

I wonder if this is just my (windows) machine, or if there is someone else who can reproduce this.

**Comment by dilijev** [comment]
@bterlson Is this a bug in https://github.com/bterlson/test262-harness or eshost?

**Comment by bterlson** [comment]
Should be addressed in v2.4.1 at least? It doesn't repro for me.

**Comment by rwaldron** [comment]
This issue is fully resolved in v2.6.0 of https://github.com/bterlson/test262-harness

**Comment by bterlson** [comment]
I'm still very confused as to why it was no repro on my machine. Oh well.
