### ISSUE TITLE
Can we avoid wrapping code on `-e`?

### ISSUE THREAD

**Issue by leobalter** [bterlson/eshost#13]
This is a question. Can we avoid wrapping the given code using the `-e` option?

If that's too complex to fix, it's alright (to close)

```
[~/dev/test262] (master)
$ eshost -e "({})+({})"
#### d8
[object Object][object Object]

#### jsshell
[object Object][object Object]

#### node
[object Object][object Object]

[~/dev/test262] (master)
$ eshost -e "eval('{}+{}')"
#### d8
NaN

#### jsshell
NaN

#### node
NaN
```

**Comment by dilijev** [comment]
Assuming you mean the provided code should not be wrapped in `print`? Maybe to preserve current behavior of `-e`, add another flag that takes code and doesn't wrap it in print. Maybe `-x` for eXecute (no implicit print) as a pair with `-e` for Eval?
