### ISSUE TITLE
ConsoleAgent passes the path first, which doesn't work with node

### ISSUE THREAD

**Issue by ljharb** [bterlson/eshost#31]
When I try to run my [finally](https://github.com/tc39/test262/pull/1156) tests with test262-harness, passing `--hostArgs='--harmony_promise_finally'` fails. However, when I edit [this line](https://github.com/bterlson/eshost/blob/master/lib/ConsoleAgent.js#L18) in ConsoleAgent to be `args = this.args.concat(args)`, it passes.

In other words, I think the tempfile path needs to be the last argument passed, at least in node.

**Comment by rwaldron** [comment]
See also: https://github.com/tc39/test262/pull/1156#issuecomment-318425139

I have a patch written for this, I'm just working out some testing details with @jugglinmike

**Comment by bterlson** [comment]
I think I also fixed this in the modules branch, fwiw: https://github.com/bterlson/eshost/commit/6feab854abc92f36ed181745a2e3d5882b37a561#diff-bdbdfde5f543e4aca41ea83a7b18a3d9R17 (and related functionality).

**Comment by rwaldron** [comment]
My patch is super simple...

(in agents/node.js)
```js
class NodeAgent extends ConsoleAgent {
  createChildProcess(args) {
    return cp.spawn(this.hostPath, this.args.concat(args || []));
  }
```

**Comment by rwaldron** [comment]
This issue also affects:

- chakra 
- d8 (obviously)
- jsc
- jsshell

**Comment by bterlson** [comment]
@rwaldron this issue is resolved right? I guess "fixes gh-31" doesn't auto-close #31.

**Comment by ljharb** [comment]
@bterlson https://github.com/bterlson/eshost/pull/34 isn't merged yet; it will auto-close once it hits master.

**Comment by bterlson** [comment]
@ljharb ahh right, thanks. Guess that's blocked on making the tests pass.

**Comment by rwaldron** [comment]
Yep, I'm tracking all of this on my end. I just resolved the ChakraCore --debug build requirement, waiting on CI.
