### ISSUE TITLE
Fix Readme documentation: createAgent returns a promise

### ISSUE THREAD

**Issue by leobalter** [bterlson/eshost#43]
The [readme documentation](https://github.com/bterlson/eshost#createagenttype-string-options---runner) says createAgent will return a Runner agent, but it's actually a promise that will be resolved to this Runner.

`createAgent` returns the result of `Agent#initialize()`, which is a Promise.resolve call.

The examples are also slightly wrong:

```js
const agent = esh.createAgent('d8', { hostPath: 'path/to/d8.exe' });
const result = await agent.evalScript(`
  print(1+1);
`);
```

`agent` is a promise, so we need to add an await for createAgent as well:

```js
const agent = await esh.createAgent('d8', { hostPath: 'path/to/d8.exe' });
const result = await agent.evalScript(`
  print(1+1);
`);
```

**Comment by bterlson** [comment]
GOOD CATCH

**Comment by leobalter** [comment]
that was probably the most exciting answer I ever got from a bug report. I'm glad to see it's fixed.
