### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by leobalter** [bterlson/eshost#54]
I need to re-use some of the work from this repo, but I need a valid OS license. Not being a GPLv3 would be great.

@bterlson I can also send a PR with a license if you tell me which one to use.

**Comment by rwaldron** [comment]
https://github.com/bterlson/eshost/blob/master/package.json#L11?

**Comment by leobalter** [comment]
that's a hint for MIT, but I think it might not be enough for licensing.

**Comment by rwaldron** [comment]
Gotcha

**Comment by bterlson** [comment]
MIT is fine by me. Also ok with ISC.

**Comment by rwaldron** [comment]
https://github.com/bterlson/eshost/blob/master/LICENSE
