### ISSUE TITLE
Runner.js should use absolute paths

### ISSUE THREAD

**Issue by evilpie** [bterlson/eshost#7]
This https://github.com/bterlson/es-host-wrapper/blob/master/lib/Runner.js#L15-L20 doesn't work for me on Linux. We end up in right directory, but the binary isn't executed, because it is trying to find the binary in the global path.

```
args = args || [];
args = args.concat(this.args);
const proc = cp.spawn(this.hostPath, args);
return proc;
```

**Comment by bterlson** [comment]
Done :)
