### ISSUE TITLE
Handling negative zero in print function

### ISSUE THREAD

**Issue by chicoxyzzy** [bterlson/eshost#75]
```
➜ eshost -itsx 'print(-0)'
## Source
print(-0)

┌─────┬───┐
│ ch  │ 0 │
│ jsc │   │
│ sm  │   │
│ v8  │   │
│ xs  │   │
└─────┴───┘
```

In fact result should be `-0` (as it happens in all browser consoles), but `-0` coerces to String somewhere. Probably this should be special-cased.

**Comment by rwaldron** [comment]
This isn't a bug in eshost: 

```
$ jsc
>>> -0
0
>>> print(-0)
0
undefined
>>>

$ sm
js> -0
-0
js> print(-0)
0
js>

$ v8
V8 version 7.5.45
d8> -0
0
d8> print(-0)
0
undefined
```

**Comment by chicoxyzzy** [comment]
Oh I didn't `print` is integrated into js shells (along with `read`, `load` and possibly others)
